-- 코드를 입력하세요
SELECT PRODUCT_CODE, (PRICE*SUM(SALES_AMOUNT)) AS SALES
FROM PRODUCT PR LEFT JOIN OFFLINE_SALE OS 
ON OS.PRODUCT_ID = PR.PRODUCT_ID 
GROUP BY PRODUCT_CODE
HAVING SALES IS NOT NULL
ORDER BY SALES DESC, PRODUCT_CODE